version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@3.2.2

jobs:
  build:
    docker:
    - image: cimg/base:2024.11
    steps:
    - run:
        name: Set Branch Environment Variable 
        command: |
          if test "$CIRCLE_BRANCH" == "main"
          then
            echo 'export BUILD="production"' >> "$BASH_ENV"
          else
            echo 'export BUILD="$GCP_BRANCH"' >> "$BASH_ENV"
          fi
          source "$BASH_ENV"
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - gcp-cli/setup:
        gcloud_service_key: GCP_KEY
        google_compute_region: GCP_REGION
        google_project_id: GCP_PROJID
    - run: 
        name: "Authenticate Docker For GCP"
        command: gcloud auth configure-docker australia-southeast1-docker.pkg.dev
    - run:
        name: "Build Image"
        command: |
          TAG=$GCP_ARTURL/$BUILD:$CIRCLE_SHA1
          docker build -t $TAG .
    - run:
        name: "Push Image"
        command: |
          TAG=$GCP_ARTURL/$BUILD:$CIRCLE_SHA1
          docker push $TAG
  deploy:
    docker:
    - image: cimg/base:2024.11
    steps:
    - run:
        name: Set Branch Environment Variable 
        command: |
          if test "$CIRCLE_BRANCH" == "main"
          then
            echo 'export BUILD="production"' >> "$BASH_ENV"
          else
            echo 'export BUILD="$GCP_BRANCH"' >> "$BASH_ENV"
          fi
          source "$BASH_ENV"
    - gcp-cli/setup:
        gcloud_service_key: GCP_KEY
        google_compute_region: GCP_REGION
        google_project_id: GCP_PROJID
    - run:
        name: "Deploy New Revision"
        command: |
          TAG=$GCP_ARTURL/$BUILD:$CIRCLE_SHA1
          BUCKET=$BUILD-persona-net-static
          gcloud run deploy $BUILD \
            --image=$TAG \
            --region=$GCP_REGION \
            --add-volume=name=static,type=cloud-storage,bucket=$BUCKET \
            --add-volume-mount=volume=static,mount-path=/app/static 

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - staging
      - deploy:
          requires:
            - build
